---
title: 'LING 4220: Acoustic Phonetics'
output: html_document
---

-----

An investigation of acoustic-phonetic aspects of speech and their relation to speech perception and recognition. Practical experience in techniques of acoustic-phonetic research.

Prerequisite: AP/LING 2110 3.0 and AP/LING 2120 3.0 with grades of C+ or better, and at least six credits in linguistics (LING) at the 3000-level with grades of C+ or higher, or permission of the department. AP/LING 3120 3.0 is recommended.

<br>

-----

<h3> [Lab 1 - Exploring Praat](acoustic_phonetics_labs/new_labs/Lab1.html) </h3> 
The goal of this first lab is to explore some of the basic features of [PRAAT](www.praat.org), which we will be using for speech analysis throughout the term. You will learn to make recordings, bring up visual displays of these recordings (waveforms and spectrograms), segment and label various components of these recordings, and export the visual displays into a word document.

Readings to prepare for this lab are:

* Johnson (2012). Chapter 1.
* Baart (2011). Chapter 2.3, 2.4 & 4.2.

<br>

<h3> [Lab 2 - Voicing in Stop Consonants](acoustic_phonetics_labs/new_labs/Lab2.html) </h3> 
Blurb can go here!


<br>

<h3> [Lab 3 - Vowel Properties](acoustic_phonetics_labs/new_labs/Lab3.html) </h3> 
Blurb can go here!


<br>

<h3> [Lab 4 - The Source-Filter Model of Speech: Fundamental frequency, harmonics and formants](acoustic_phonetics_labs/new_labs/Lab4.html) </h3> 
Blurb can go here!

<br>

<h3> [Lab 5 - Glides and Liquids](acoustic_phonetics_labs/new_labs/Lab5.html) </h3> 
Blurb can go here!

<br>

<h3> [Lab 6 - Obstruent Place of Articulation](acoustic_phonetics_labs/new_labs/Lab6.html) </h3> 
Blurb can go here!


<br>

<h3> [Lab 7 - Phonation Types](acoustic_phonetics_labs/new_labs/Lab7.html) </h3> 
Blurb can go here!


<br>

<h3> [Lab 8 - Nasals](acoustic_phonetics_labs/new_labs/Lab8.html) </h3> 
Blurb can go here!

