---
title: "Papers, posters, and presentations"
---

<br>

#### 2025

[[slides](papers_etc/Kettig2025NWAV-AP_slides.pdf)] Kettig, Thomas. 2025. Internal linguistic conditioning of /t~k/ variation in Niʻihau Hawaiian. _NWAV-AP 8_. Singapore, 5 August.

[[paper](https://eprints.whiterose.ac.uk/id/eprint/226525/)] Hughes, Vincent, Carmen Llamas, and Thomas Kettig. Human and automatic voice comparison with regionally variable speech samples. _Speech Communication_ 172.

[[slides](papers_etc/Kettig2025CLS_slides.pdf)] Kettig, Thomas. Niʻihau Hawaiian /t/>[k] allophony is driven by coronal dissimilation. _CLS61_. Chicago, IL, 9 May. 

[[slides](papers_etc/Kettig2025moth_slides.pdf)] Kettig, Thomas. Dissimilation of /t/ to [k] in Niʻihau Hawaiian. _[motʰ]_ 2025. Toronto, ON, 4 April. 

[[workshop slides](papers_etc/ChengEtAl2025_talkstory.pdf)] Cheng, Andrew, Lisa Davidson, ‘Ōiwi Parker Jones, Thomas Kettig, and Noah Haʻalilio Solomon. ʻŌlelo aku, ʻōlelo mai: Building reciprocity into ʻōlelo Hawaiʻi pronunciation rsearch. _ICLDC9_. Honolulu, HI, 9 March.

<br>

#### 2024

[[abstract](papers_etc/KettigDavidson2024LabPhon19_abstract.pdf)]
[[poster](papers_etc/KettigDavidson2024LabPhon_Poster.jpg)] Kettig, Thomas, and Lisa Davidson. 2024. Acoustic correlates of stress in contrastive short and long vowels in ʻōlelo Hawaiʻi. _LabPhon19_. Seoul, Korea, 27–29 June. 

[[slides](papers_etc/KettigDavidson2024AFLA_slides.pdf)] Kettig, Thomas, and Lisa Davidson. 2024. Stress and contrastive length are distinctively cued in ʻōlelo Hawaiʻi vowels. _AFLA31_. Amherst, MA, 12–14 June.

[[slides](papers_etc/KettigDavidson2024LSA_slides.pdf)] Kettig, Thomas, and Lisa Davidson. 2024. Acoustic correlates distinguish multiple levels of stress in ʻōlelo Hawaiʻi. _100th Annual Meeting of the Linguistic Society of America_. New York, NY, 5 January.  


<br>

#### 2023

[[paper](https://osf.io/preprints/psyarxiv/q8t2k)] Coretta, Stefano, Joseph Casillas, … Thomas Kettig, … Timo Roettger. 2023. Multidimensional signals and analytic flexibility: Estimating degrees of freedom in human speech analyses. _Advances in Methods and Practices in Psychological Science_.  

[[slides](papers_etc/Kettig2023NWAV51_slides.pdf)] Kettig, Thomas. 2023. Inter- and intra-speaker /ai~ei/ variation in ʻōlelo Hawaiʻi. Acoustic and historical-comparative evidence. _NWAV 51_, New York, NY, 14 October.  

[[abstract](papers_etc/Kettig2023ICPhS_abstract.pdf)] [[slides](papers_etc/Kettig2023ICPhS_slides.pdf)] Kettig, Thomas. 2023. Word class and frequency effects in Hawaiian stressed vowel clusters. _International Congress of Phonetic Sciences 2023_. Prague, Czechia, 9 August.

<br>

#### 2022
[[slides](papers_etc/Kettig2022NWAV50_slides.pdf)] Kettig, Thomas. 2022. Word class and diphthong reduction in ʻōlelo Hawaiʻi. _NWAV 50_. San Jose, CA, USA, 14 October.  

[[abstract](https://vincent-hughes.com/wp-content/uploads/2022/06/490_paper.pdf)] Hughes, Vincent, Carmen Llamas, and Thomas Kettig. 2022. Eliciting and evaluating likelihood ratios for speaker recognition by human listeners under forensically realistic channel-mismatched conditions. _Proceedings of Interspeech_. Incheon, Korea.  

[[abstract](papers_etc/HughesLlamasKettig2022IAFPA30_abstract.pdf)] Hughes, Vincent, Carmen Llamas, and Thomas Kettig. 2022. A game-based approach to eliciting and evaluating likelihood ratios for speaker recognition. _30th Annual Conference of the International Association for Forensic Phonetics and Acoustics_. Prague, Czechia, 10-13 July.  

<br>

#### 2021

Barreda, Santiago, Thomas Kettig, and Chaya Nove. 2021. Workshop: Improving vowel formant analysis in sociophonetic research using Fast Track. _NWAV 49_. Online, 19 October.  

[[video](https://youtu.be/PdPxQGXSX64?si=L9T25u1TVCq-kIXl)] Kettig, Thomas. 2021. Nānā i ke kumu: Acoustic phonetic research on archival recordings of ʻōlelo Hawaiʻi. _International Conference on Language Documentation and Conservation 7_. Online.  

[[paper](https://scholarspace.manoa.hawaii.edu/server/api/core/bitstreams/49cdaa29-f832-43d3-bb57-1c2b7d5694f3/content)] Kettig, Thomas. 2021. Haʻina ʻia mai ana ka puana: The vowels of ʻōlelo Hawaiʻi. PhD Dissertation, University of Hawaiʻi at Mānoa.  

[[link](https://doi.org/10.1017/9781108644198)] Drager, Katie and Thomas Kettig. 2021. Trends in Sociophonetics. In R.-A. Knight and J. Setter (eds), _Cambridge Handbook of Phonetics. Cambridge: Cambridge University Press_, pp. 551-577.  

<br>

#### 2019

[[abstract](https://assta.org/proceedings/ICPhS2019/papers/ICPhS_3607.pdf)] [[poster](papers_etc/Kettig2019ICPhS_poster.pdf)] Kettig, Thomas. 2019. Spectral coarticulation in Hawaiian /aV/ and /aCV/ sequences. _International Congress of Phonetic Sciences 2019_. Melbourne, Australia, 8 August. (Poster)

<br>

#### 2018

[[slides](papers_etc/KettigDrager2018SocioSymposium22_slides.pptx)] Kettig, Thomas and Katie Drager. 2018. The social evaluation of TRAP-backing in Montreal. _Sociolinguistics Symposium 22_. Auckland, New Zealand, 30 June.  

<br>

#### 2017

[[paper](papers_etc/Kettig2017Now_Say_Ah.pdf)] Kettig, Thomas. 2017. “Now say ‘Ah’: Internal factors of shifting and the English low vowel space.” E. Louviot & C. Delesse (eds), _Studies in Language Variation and Change 2 Shifting, Switching and Alternating Patterns in the History of English_. Newcastle upon Tyne: Cambridge Scholars Publishing.  

[[poster](papers_etc/Kettig2017PAPE_poster.pdf)] Kettig, Thomas. 2017. “Diachronically stable, lexically specific variation: The phonological representation of secondary /æ/-lengthening”. _Phonetics and Phonology in Europe_. Cologne, Germany, 12-14 June. (Poster)  

[[paper](papers_etc/KettigWinter2017LVC.pdf)]  Kettig, Thomas and Bodo Winter. 2017. “Producing and Perceiving the Canadian Vowel Shift: Evidence from a Montreal Community.” _Language Variation and Change_ 29(1): 79–100. DOI:[https://doi.org/10.1017/S0954394517000023](https://doi.org/10.1017/S0954394517000023.) https://doi.org/10.1017/S0954394517000023.  

[[poster](papers_etc/Kettig2017LSA_poster.pdf)] Kettig, Thomas. 2017. “One hundred years of stability: The case of the BAD-LAD split”. _91st Annual Meeting of the Linguistic Society of America. Austin, TX, 6 January_. (Poster)  

<br>

#### 2016

[[paper](http://dx.doi.org/10.1080/00472336.2015.1028964)] Kettig, Thomas, Sarah Turner, Đinh Thị Diệu and Phạm Văn Cự. 2016. “State Livelihood Planning and Legibility in Vietnam’s Northern Borderlands: The ‘Rightful Criticisms’ of Local Officials.” _Journal of Contemporary Asia_ 46(1): 42–70. DOI: [http://dx.doi.org/10.1080/00472336.2015.1028964](http://dx.doi.org/10.1080/00472336.2015.1028964)

[[slides](papers_etc/Kettig2016SocioSymposium21_slides.pdf)] Kettig, Thomas. 2016. “Preaspiration following /æ/ in Southern Standard British English.” _Sociolinguistics Symposium_ 21. Murcia, Spain, 15–18 June.  

[[poster](papers_etc/Kettig2016LSA_poster.pdf)] [[extended abstract](https://doi.org/10.3765/plsa.v1i0.3732)] Kettig, Thomas. 2016. “The BAD-LAD split: Secondary /æ/-lengthening in Southern Standard British English” (Poster). _90th Annual Meeting of the Linguistic Society of America_. Washington, DC, 8 January. DOI: [http://dx.doi.org/10.3765/plsa.v1i0.3732.](http://dx.doi.org/10.3765/plsa.v1i0.3732)  

[[paper](papers_etc/Kettig2016MPhil.pdf)] Kettig, Thomas. The BAD-LAD Split: A Phonetic Investigation. Masters Thesis, University of Cambridge.  

<br>

#### 2015

Kettig, Thomas and Bodo Winter. 2015. “The Canadian Vowel Shift in Production and Perception: New Evidence from Montreal.” _NWAV44: Intersections_. Toronto, ON, 22-25 October 2015.

[[slides](papers_etc/Kettig2015Now_Say_Ah_slides.pdf)] Kettig, Thomas. 2015. “Now say ‘Ah’: Internal factors of shifting and the English low vowel space.” _4th Biennial Conference on the Diachrony of English_. Troyes, France, 6 July.

[[slides](papers_etc/KettigWinter2015ExLing_slides.pdf)] Kettig, Thomas and Bodo Winter. 2015. “Production and Perception Asymmetries in the Canadian Vowel Shift.” _6th International Conference on Experimental Linguistics_. Athens, Greece, 26 June.

[[link](papers_etc/Kettig2015SocioSymposium20_slides.pdf)] Kettig, Thomas. 2015. “Changing Accents, Changing Vowels.” _St Edmund’s Interdisciplinary Conference_. St Edmund’s College, Cambridge, UK, 19 February.

<br>

#### 2014

[[slides](papers_etc/Kettig2014SocioSymposium20_slides.pdf)] Kettig, Thomas. 2014. “Gussing Rondomly: How Canadians are advancing, spreading, and perceiving an active vowel shift.” _Sociolinguistics Symposium 20. Jyväskylä_, Finland, 18 June.

[[slides](papers_etc/Kettig2014ADS_slides.pdf)] Kettig, Thomas. 2014. The Canadian Short Vowels in Motion: Real-time Change and Regional Diffusion. _2014 Annual Meeting of the American Dialect Society_. Minneapolis, MN, 2 January.

[[slides](papers_etc/Kettig2014LSA_slides.pdf)] [[abstract](papers_etc/Kettig2014LSA_abstract.pdf)] Kettig, Thomas. 2014. “The Canadian Shift: Its Acoustic Trajectory and Consequences for Vowel Categorization.” _88th Annual Meeting of the Linguistic Society of America_. Minneapolis, MN, 4 January. DOI:[http://dx.doi.org/10.3765/exabs.v0i0.2386.](http://dx.doi.org/10.3765/exabs.v0i0.2386)

<br>

#### 2013

[[paper](papers_etc/Kettig2013UndergradThesis.pdf)] Kettig, Thomas. 2013. "The Canadian Shift in a Montreal Community: Change and Variation in Perception and Production of the Non-Hight Short Vowels." Undergraduate thesis, McGill University.

[[slides](papers_etc/Kettig2013McCCLU_slides.pdf)] Kettig, Thomas. 2013. “Production and Perception of Short Vowels in Montréal.” _McGill Canadian Conference for Linguistics Undergraduates_. Montréal, QC, 18 March.
